name = "food-analyzer-app"
compatibility_date = "2024-03-01"

[env.production.vars]
# Environment variables will be set in Cloudflare Pages dashboard
# GEMINI_API_KEY is configured in dashboard (not REACT_APP_ prefixed for security)

[[env.production.pages_build_output_dir]]
directory = "build"